name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.76.0
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests (with coverage)
        run: cargo llvm-cov --lcov --output-path ./lcov.info
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      - name: Upload tests coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

  test_documentation:
    name: Test Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.76.0
      - name: Run documentation tests
        run: make test-doc
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}

  test_examples:
    name: Test Examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.76.0
      - name: Run examples
        run: make test-examples
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
